### ISSUE TITLE
Doesn't work with Post-processing stack v2

### ISSUE THREAD

**Issue by alxdncn** [Looking-Glass/HoloplaySDK_Issues#44]

**Comment by alxdncn** [comment]
Several people are asking for support for this on the forums.

**Comment by Albert** [comment]
For reference, here's one such post: https://forum.lookingglassfactory.com/t/unity-post-processing-on-looking-glass/909/9

It sounds like the issue is that Unity's Post-Processing V1 used to work for the older version of HoloPlay (0.1.4).  Folks who upgraded to HoloPlay 1.0 now see that the feature is no longer supported.

Unity's Post-Processing V2 is still under development, so we'll support that when it's more stable.

**Comment by andybak** [comment]
> Unity's Post-Processing V2 is still under development, so we'll support that when it's more stable.

You'd better hurry up. PPv2 is now relegated to working with the Legacy Renderer and all the real action is happening with the Scriptable Render Pipelines which have their own built-in Post-processing.

So - will we get support for either PPv2 or HDRP any time soon?

**Comment by alxdncn** [comment]
Fixed on upcoming release of the SDK, v1.2.0 - it has a custom implementation of the V2 of the post-processing stack that is compatible with the HoloPlay SDK.
